## Load libraries

In [50]:
import pandas as pd
import plotly.graph_objects as go
from plotly.subplots import make_subplots
import os
import shutil

In [51]:
##Load data. In this analisis just use Glucose condition. 
BP_glucose = pd.read_excel('/home/notebooks/Notebooks/LIZ/Ntbooks_finales/infiles/BP_Results_Glucose.xlsx')
print(len(BP_glucose))
BP_glucose.head(2)

117

,GO.ID,term,definition,Essential.genes_frequency,Essential.pvalue,Essential.-log10_pvalue,Essential.Significant_genes,Essential.Significant_genes_symbol,Important.genes_frequency,Important.pvalue,...,No_effect.genes_frequency,No_effect.pvalue,No_effect.-log10_pvalue,No_effect.Significant_genes,No_effect.Significant_genes_symbol,Fitness_enhancing.genes_frequency,Fitness_enhancing.pvalue,Fitness_enhancing.-log10_pvalue,Fitness_enhancing.Significant_genes,Fitness_enhancing.Significant_genes_symbol
0,GO:0006633,fatty acid biosynthetic process,The chemical reactions and pathways resulting ...,46.154% (12/26),0.000014,4.85,944805;944888;944895;945568;945645;945766;9458...,acpP;fabZ;accA;fabA;fabG;fabD;fabI;accD;fabB;a...,3.846% (1/26),0.760267,...,34.615% (9/26),0.999997,0.0,NaN,NaN,3.846% (1/26),0.229255,0.64,NaN,NaN
1,GO:0072525,pyridine-containing compound biosynthetic process,The chemical reactions and pathways resulting ...,34.783% (8/23),0.003656,2.44,944919;945060;945248;945527;946785;946946;9470...,pdxA;dxs;nadD;serC;pdxB;nadE;pdxJ;nadK,17.391% (4/23),0.031078,...,43.478% (10/23),0.999720,0.0,NaN,NaN,0% (0/23),1.000000,0.00,NaN,NaN

In [52]:
#
d_essen = BP_glucose.iloc[:, [0, 7]].set_index(BP_glucose.columns[0]).to_dict()[BP_glucose.columns[7]]
d_impor = BP_glucose.iloc[:, [0, 12]].set_index(BP_glucose.columns[0]).to_dict()[BP_glucose.columns[12]]
d_noeff = BP_glucose.iloc[:, [0, 17]].set_index(BP_glucose.columns[0]).to_dict()[BP_glucose.columns[17]]
d_enhan = BP_glucose.iloc[:, [0, 22]].set_index(BP_glucose.columns[0]).to_dict()[BP_glucose.columns[22]]

main_dict = {
    "Essential": d_essen,
    "Important": d_impor,
    "No effect": d_noeff,
    "Enhancing": d_enhan
}

for key, sub_dict in main_dict.items():
    main_dict[key] = {k: v for k, v in sub_dict.items() if pd.notna(v)}
    gos = len(main_dict[key])
    #print(f"{key} tiene {gos} process")
    
    for sub_key, sub_value in main_dict[key].items():
        print(f"{sub_key} ")    
    print()

GO:0006633
GO:0072525
GO:0033875
GO:0044249
GO:0051649
GO:0045229
GO:0009152
GO:0009156
GO:0015949
GO:0009185
GO:0022402
GO:0032984
GO:0006757
GO:0006553
GO:0061024
GO:0006575
GO:0034032
GO:0006090
GO:0072657
GO:0042364
GO:0009067
GO:0051301
GO:0009082
GO:0009084
GO:0000097
GO:0009070
GO:0009073
GO:0043650
GO:0009260
GO:0008652
GO:0008654
GO:0009252
GO:0042558
GO:0006260
GO:0006261
GO:1901607
GO:0043648
GO:0000027
GO:0000028
GO:0017148
GO:0006412
GO:0006418
GO:0006221
GO:0009245
GO:1901566
GO:0065008
GO:0043604
GO:0033014
GO:0008360
GO:0044283
GO:1901576
GO:0006400
GO:0044272

GO:0042364
GO:0009082
GO:0044272
GO:0072528
GO:0034308
GO:0050790
GO:0006163
GO:0098660
GO:0009314
GO:0050789
GO:0046496
GO:0006310
GO:0032506
GO:0019058
GO:1901617
GO:0015833
GO:0051701
GO:0009244
GO:0000041
GO:0006402

GO:0071973
GO:0009061
GO:0044780
GO:0015718
GO:0010035
GO:1902074
GO:2001057
GO:0015749
GO:1902021
GO:0042710
GO:0043711
GO:0046395
GO:1905039
GO:0007165
GO:0055085
GO:0046113
GO:0043709
GO:1901700
GO:0062197
GO:0098739
GO:0034310
GO:0035672
GO:1901136
GO:0015850
GO:0006355
GO:0098655
GO:0006865
GO:0008643
GO:0044282
GO:0044275
GO:0072329
GO:0006814
GO:0034219
GO:0140352
GO:0044242
GO:0006974
GO:1902475
GO:0042938
GO:0022900
GO:0019400
GO:0046434
GO:0042908
GO:0006935
GO:1901565
GO:0042402

GO:0006355
GO:0009628
GO:0016226

In [53]:
df_gen = pd.DataFrame(columns=['Categ', 'GO', 'genes'])

for key, sub_dict in main_dict.items():
    main_dict[key] = {k: v for k, v in sub_dict.items() if pd.notna(v)}
    for sub_key, sub_value in main_dict[key].items():
        df_gen = pd.concat([df_gen, pd.DataFrame({'Categ': [key], 'GO': [sub_key], 'genes': [sub_value]})], ignore_index=True)
        #print(f"{sub_key}: {sub_value}")
df_gen

         Categ          GO                                              genes
0    Essential  GO:0006633  acpP;fabZ;accA;fabA;fabG;fabD;fabI;accD;fabB;a...
1    Essential  GO:0072525             pdxA;dxs;nadD;serC;pdxB;nadE;pdxJ;nadK
2    Essential  GO:0033875        accA;accD;relA;coaD;accC;coaA;cysQ;dfp;coaE
3    Essential  GO:0044249  aroK;ileS;dapB;carB;ispH;folA;murE;leuB;ftsI;l...
4    Essential  GO:0051649  secA;fes;fepC;fepG;fepD;ffh;fepB;secY;ftsY;sec...
..         ...         ...                                                ...
116  No effect  GO:1901565  cyuA;tdcG;sspB;rihC;ldcC;ltaE;mltA;ybcF;eutH;y...
117  No effect  GO:0042402  eutH;puuE;patD;puuD;puuR;feaB;tynA;speG;puuA;e...
118  Enhancing  GO:0006355         iscR;cspC;yebK;rpoS;gcvA;fis;rbsR;rapA;hfq
119  Enhancing  GO:0009628             gloB;osmC;sufC;pykF;yebG;grpE;gcvA;fis
120  Enhancing  GO:0016226                                sufD;sufB;sufC;sufE

[121 rows x 3 columns]

In [54]:
def sum_pl3(my_list, condition):  #select a list with the file name and condition
    eco_db4691_final = "~/Notebooks/LIZ/COG/allgen4691_fitfg_newname.csv"
    proteomic = "~/Notebooks/LIZ/COG/proteo2346.csv"
    
    all_db =  pd.read_csv(eco_db4691_final)
    total_proteo = all_db.sum(numeric_only=True)
    df = pd.read_csv(my_list)
    df2 = pd.read_csv(proteomic)
    lista2 = list(df["genes"])
    matching_genes = all_db[all_db["gene"].isin(lista2)]
    PL = matching_genes[condition].sum(numeric_only=True)
    tgenes = len(lista2)
    mw_prote = df2[df2["gen"].isin(lista2)]
    genes_withpl = len(mw_prote)
    proteome_fraction = (PL / total_proteo[condition]) * 100
    
    return proteome_fraction

In [55]:
output = "Results_fdf"
os.makedirs(output, exist_ok=True)
seen_sub_keys = set()
df_len = pd.DataFrame(columns=['categ', 'GO', 'len'])
unique_sub_keys = set() 

for key, sub_dict in main_dict.items():
    main_dict[key] = {k: v for k, v in sub_dict.items() if pd.notna(v)}
    for sub_key, sub_value in main_dict[key].items():
        sub_values_list = sub_value.split(';')
        l_gos = len(sub_values_list)       
        genes_df = pd.DataFrame({'genes': sub_values_list})
        output_file = os.path.join(output, f"{key}_{sub_key}.csv")
        
        if sub_key not in seen_sub_keys:
            seen_sub_keys.add(sub_key)               
            df_len = pd.concat([df_len, pd.DataFrame({'categ': [key], 'GO': [sub_key], 'len': [l_gos]})], ignore_index=True)
        # print(key, sub_key, l_gos)
        genes_df.to_csv(output_file, index=False)
df_len

         categ          GO  len
0    Essential  GO:0006633   12
1    Essential  GO:0072525    8
2    Essential  GO:0033875    9
3    Essential  GO:0044249  294
4    Essential  GO:0051649   11
..         ...         ...  ...
112  No effect  GO:0006935   24
113  No effect  GO:1901565  183
114  No effect  GO:0042402   27
115  Enhancing  GO:0009628    8
116  Enhancing  GO:0016226    4

[117 rows x 3 columns]

## Calcular la suma de carga proteómica por cada uno de los procesos identificados en el enriquecimiento.

In [56]:
folder_path = "./Results_fdf/"
df_PL = pd.DataFrame(columns=['Categ', 'GO', 'PF'])

for file_name in os.listdir(folder_path):
    if file_name.endswith(".csv"):
        file_path = os.path.join(folder_path, file_name)
        split_filename = file_name.split('_')
        Categ = split_filename[0]
        GO = split_filename[1].split('.')[0]
        
        results_Fracprot = sum_pl3(file_path, 'Glucose')
        df_PL = pd.concat([df_PL, pd.DataFrame({'Categ': [Categ], 'GO': [GO], 'PF': [results_Fracprot]})], 
                          ignore_index=True)
shutil.rmtree(folder_path)
df_PL

         Categ          GO        PF
0    No effect  GO:1901700  1.714804
1    Important  GO:0015833  0.098890
2    Essential  GO:0000027  2.734707
3    Essential  GO:0000028  3.220307
4    Essential  GO:0032984  1.072191
..         ...         ...       ...
116  Important  GO:0050790  0.112990
117  Essential  GO:0061024  0.313641
118  Essential  GO:0051649  0.168155
119  Essential  GO:0042558  3.379502
120  Important  GO:0009244  0.152839

[121 rows x 3 columns]

In [57]:
d_essen = BP_glucose.iloc[:, [0, 3]].set_index(BP_glucose.columns[0]).to_dict()[BP_glucose.columns[3]]
d_impor = BP_glucose.iloc[:, [0, 8]].set_index(BP_glucose.columns[0]).to_dict()[BP_glucose.columns[8]]
d_noeff = BP_glucose.iloc[:, [0, 13]].set_index(BP_glucose.columns[0]).to_dict()[BP_glucose.columns[13]]
d_enhan = BP_glucose.iloc[:, [0, 18]].set_index(BP_glucose.columns[0]).to_dict()[BP_glucose.columns[18]]

main_dict2 = {
    "Essential": d_essen,
    "Important": d_impor,
    "No effect": d_noeff,
    "Enhancing": d_enhan
}

df_gos = pd.DataFrame(columns=['Categ', 'GO', 'percent'])
for key, sub_dict in main_dict2.items():
    main_dict[key] = {k: v for k, v in sub_dict.items() if pd.notna(v)}

    for sub_key, sub_value in main_dict[key].items():
        sub_values_list = sub_value.split(' ')
        percent = sub_values_list[0]
        df_gos = pd.concat([df_gos, pd.DataFrame({'Categ': [key], 'GO': [sub_key], 'percent': [percent]})], ignore_index=True)
        #print(f"{sub_key}: {sub_value}")

df_gos['percent'] = df_gos['percent'].str.rstrip('%').astype(float)
df_fil = df_gos[df_gos['percent'] > 0]
df_fil

         Categ          GO  percent
0    Essential  GO:0006633   46.154
1    Essential  GO:0072525   34.783
2    Essential  GO:0033875   39.130
3    Essential  GO:0044249   26.703
4    Essential  GO:0051649   27.500
..         ...         ...      ...
456  Enhancing  GO:0006974    0.735
459  Enhancing  GO:0022900    1.031
464  Enhancing  GO:1901565    0.971
466  Enhancing  GO:0009628    3.162
467  Enhancing  GO:0016226   19.048

[350 rows x 3 columns]

In [58]:
df_result = pd.merge(df_PL, df_fil[['Categ', 'GO', 'percent']], on=['Categ', 'GO'], how='left')
funciones = BP_glucose.loc[:,('GO.ID','term')]
funciones.rename(columns={"GO.ID": "GO"}, inplace=True)
df_func = pd.merge(df_result, funciones, on='GO', how='left')
df_func.head(52)

,Categ,GO,PF,percent,term
0,No effect,GO:1901700,1.714804,86.905,response to oxygen-containing compound
1,Important,GO:0015833,0.098890,14.286,peptide transport
2,Essential,GO:0000027,2.734707,53.571,ribosomal large subunit assembly
3,Essential,GO:0000028,3.220307,61.905,ribosomal small subunit assembly
4,Essential,GO:0032984,1.072191,28.205,protein-containing complex disassembly
5,Essential,GO:0009185,4.467332,43.478,ribonucleoside diphosphate metabolic process
6,Essential,GO:0009152,1.189917,41.860,purine ribonucleotide biosynthetic process
7,No effect,GO:0044242,0.045167,93.750,cellular lipid catabolic process
8,No effect,GO:0009061,0.219606,95.082,anaerobic respiration
9,Important,GO:0006310,0.133773,11.429,DNA recombination
10,Essential,GO:0072657,0.308801,50.000,protein localization to membrane
11,Essential,GO:0008360,0.177266,38.095,regulation of cell shape
12,No effect,GO:0043711,0.003625,94.737,pilus organization
13,No effect,GO:0098655,0.650470,85.047,monoatomic cation transmembrane transport
14,Essential,GO:0072525,0.627115,34.783,pyridine-containing compound biosynthetic process
15,No effect,GO:0019400,0.360344,93.750,alditol metabolic process
16,No effect,GO:0006865,2.589468,95.960,amino acid transport
17,No effect,GO:0008643,0.593243,92.742,carbohydrate transport
18,No effect,GO:2001057,0.029100,100.000,reactive nitrogen species metabolic process
19,No effect,GO:1901565,1.656866,88.835,organonitrogen compound catabolic process
20,Important,GO:0000041,0.270762,13.235,transition metal ion transport
21,Essential,GO:0006633,1.118748,46.154,fatty acid biosynthetic process
22,No effect,GO:0046434,0.315395,92.500,organophosphate catabolic process
23,Essential,GO:0000097,5.623903,38.462,sulfur amino acid biosynthetic process
24,Essential,GO:0065008,1.053044,32.500,regulation of biological quality
25,No effect,GO:1902475,0.354584,96.552,L-alpha-amino acid transmembrane transport
26,Essential,GO:0006261,0.299157,32.500,DNA-templated DNA replication
27,Essential,GO:0009067,5.386876,50.000,aspartate family amino acid biosynthetic process
28,Essential,GO:0006221,1.103947,50.000,pyrimidine nucleotide biosynthetic process
29,No effect,GO:0042938,0.234256,100.000,dipeptide transport
30,Important,GO:0072528,0.131028,23.684,pyrimidine-containing compound biosynthetic pr...
31,No effect,GO:0042710,0.361184,90.265,biofilm formation
32,Important,GO:0009314,0.096773,13.402,response to radiation
33,Important,GO:0042364,0.064134,16.667,water-soluble vitamin biosynthetic process
34,Important,GO:0044272,0.134069,16.129,sulfur compound biosynthetic process
35,Essential,GO:0006757,4.362662,35.000,ATP generation from ADP
36,Essential,GO:0006260,0.415509,34.375,DNA replication
37,Essential,GO:0006400,0.200896,23.333,tRNA modification
38,Essential,GO:1901607,12.208331,45.378,alpha-amino acid biosynthetic process
39,No effect,GO:0034219,0.556206,91.262,carbohydrate transmembrane transport
40,No effect,GO:0044780,0.006199,100.000,bacterial-type flagellum assembly
41,Essential,GO:0006090,4.482010,41.176,pyruvate metabolic process
42,No effect,GO:0044275,0.357907,90.164,cellular carbohydrate catabolic process
43,Enhancing,GO:0009628,0.521001,3.162,response to abiotic stimulus
44,No effect,GO:0098739,0.554392,87.179,import across plasma membrane
45,Essential,GO:0044249,33.501897,26.703,cellular biosynthetic process
46,Essential,GO:0008654,0.386279,48.000,phospholipid biosynthetic process
47,Essential,GO:0009245,0.248872,45.000,lipid A biosynthetic process
48,Essential,GO:0008652,12.758844,48.227,amino acid biosynthetic process
49,Essential,GO:0015949,0.357159,34.783,nucleobase-containing small molecule interconv...
50,Enhancing,GO:0016226,0.029865,19.048,iron-sulfur cluster assembly
51,Essential,GO:0034032,0.227604,39.130,purine nucleoside bisphosphate metabolic process

In [59]:
sumPB_categ = df_func.groupby('Categ')['PF'].sum().reset_index()
sumPB_categ

       Categ          PF
0  Enhancing    0.989598
1  Essential  255.130562
2  Important   14.487314
3  No effect   26.608016

In [60]:
df_func = df_func.drop(51).reset_index(drop=True) #GO:0010035, ya esta obsoleto
df_func = df_func.drop(21).reset_index(drop=True)  #GO:0006757
df_func

,Categ,GO,PF,percent,term
0,No effect,GO:1901700,1.714804,86.905,response to oxygen-containing compound
1,Important,GO:0015833,0.098890,14.286,peptide transport
2,Essential,GO:0000027,2.734707,53.571,ribosomal large subunit assembly
3,Essential,GO:0000028,3.220307,61.905,ribosomal small subunit assembly
4,Essential,GO:0032984,1.072191,28.205,protein-containing complex disassembly
...,...,...,...,...,...
114,Important,GO:0050790,0.112990,14.286,regulation of catalytic activity
115,Essential,GO:0061024,0.313641,30.303,membrane organization
116,Essential,GO:0051649,0.168155,27.500,establishment of localization in cell
117,Essential,GO:0042558,3.379502,40.000,pteridine-containing compound metabolic process
118,Important,GO:0009244,0.152839,28.000,lipopolysaccharide core region biosynthetic pr...

In [61]:
PL_sort = df_func.sort_values(by=['PF'], ascending=False)
PL_sort ##desde este df ya se cuales procesos son los que tienen mayor FP.

,Categ,GO,PF,percent,term
94,Essential,GO:1901576,35.270284,25.864,organic substance biosynthetic process
44,Essential,GO:0044249,33.501897,26.703,cellular biosynthetic process
73,Essential,GO:1901566,30.388922,40.809,organonitrogen compound biosynthetic process
61,Essential,GO:0044283,16.701492,37.171,small molecule biosynthetic process
97,Essential,GO:0043604,16.592360,43.939,amide biosynthetic process
...,...,...,...,...,...
77,No effect,GO:0140352,0.005194,90.566,export from cell
58,No effect,GO:0034310,0.004196,100.000,primary alcohol catabolic process
12,No effect,GO:0043711,0.003625,94.737,pilus organization
76,No effect,GO:1902021,0.002597,100.000,regulation of bacterial-type flagellum-depende...
68,No effect,GO:0043709,0.002504,95.349,cell adhesion involved in single-species biofi...

In [62]:
top_PL = PL_sort.groupby('Categ').head(15)
topPL = top_PL.copy()
topPL.head()

,Categ,GO,PF,percent,term
94,Essential,GO:1901576,35.270284,25.864,organic substance biosynthetic process
44,Essential,GO:0044249,33.501897,26.703,cellular biosynthetic process
73,Essential,GO:1901566,30.388922,40.809,organonitrogen compound biosynthetic process
61,Essential,GO:0044283,16.701492,37.171,small molecule biosynthetic process
97,Essential,GO:0043604,16.592360,43.939,amide biosynthetic process

In [63]:
categorias = {
    "Metabolic process": ['GO:0006355', 'GO:0006090','GO:0009185','GO:0006760','GO:0006310','GO:0022900','GO:0017148',
                         'GO:0006575','GO:0006163','GO:0046496'], 
    "Cellular process": ['GO:0016226', 'GO:0051301','GO:0032506','GO:0019058'],
     
    "Catabolic process": ['GO:0044282', 'GO:1901565', 'GO:0046395', 'GO:0044275', 'GO:0006402'],
    "Biosynthetic process": ['GO:1901566', 'GO:0043604', 'GO:0008652', 'GO:1901607', 'GO:0044272', 'GO:0000097', 
                             'GO:0009067', 'GO:0009070', 'GO:0019438', 'GO:0046394', 'GO:0009244', 'GO:0044272',
                            'GO:0072528', 'GO:1901576', 'GO:0044249', 'GO:0044283'],
    "Translation": ['GO:0006412', 'GO:0000028', 'GO:0000027'],
    "Transport": ['GO:0055085', 'GO:0015849', 'GO:0006865', 'GO:0046942', 'GO:1902600', 'GO:0008643', 'GO:0009401',
                 'GO:0034219', 'GO:0030001', 'GO:0098660', 'GO:0015833','GO:0098655','GO:0098739','GO:1905039',
                 'GO:0000041'],
    "Response to stimulus": ['GO:0009628', 'GO:0009314', 'GO:0006974', 'GO:1901700','GO:0062197'],
    "Biological regulation": ['GO:0050790', 'GO:0050790','GO:0050789'],
    "Interaction" : ['GO:0044403', 'GO:0044010', 'GO:0051701'],  
    #"Viral process" : ['GO:0019058']
}

topPL['category'] = topPL['GO'].map({GO: categoria for categoria, valores in categorias.items() for GO in valores})
for categoria in categorias:
    subset_df = topPL[topPL['category'] == categoria]
 #   print(subset_df)

In [64]:
topPL.loc[0, 'term'] = 'BP involved in interaction with host'
topPL['term'] = topPL['term'].replace('biosynthetic process', 'biosyn', regex=True)  #abbreviations: biosynth=biosynthetic
topPL['term'] = topPL['term'].replace('metabolic process', 'MP', regex=True)
topPL.head(30)

,Categ,GO,PF,percent,term,category
94,Essential,GO:1901576,35.270284,25.864,organic substance biosyn,Biosynthetic process
44,Essential,GO:0044249,33.501897,26.703,cellular biosyn,Biosynthetic process
73,Essential,GO:1901566,30.388922,40.809,organonitrogen compound biosyn,Biosynthetic process
61,Essential,GO:0044283,16.701492,37.171,small molecule biosyn,Biosynthetic process
97,Essential,GO:0043604,16.592360,43.939,amide biosyn,Biosynthetic process
53,Essential,GO:0006412,14.628048,51.370,translation,Translation
47,Essential,GO:0008652,12.758844,48.227,amino acid biosyn,Biosynthetic process
37,Essential,GO:1901607,12.208331,45.378,alpha-amino acid biosyn,Biosynthetic process
55,Essential,GO:0044272,6.499908,35.484,sulfur compound biosyn,Biosynthetic process
22,Essential,GO:0000097,5.623903,38.462,sulfur amino acid biosyn,Biosynthetic process
26,Essential,GO:0009067,5.386876,50.000,aspartate family amino acid biosyn,Biosynthetic process
103,Essential,GO:0006575,4.991999,28.889,cellular modified amino acid MP,Metabolic process
40,Essential,GO:0006090,4.482010,41.176,pyruvate MP,Metabolic process
5,Essential,GO:0009185,4.467332,43.478,ribonucleoside diphosphate MP,Metabolic process
34,Essential,GO:0006757,4.362662,35.000,ATP generation from ADP,NaN
69,Important,GO:0019058,3.970306,25.000,viral life cycle,Cellular process
59,Important,GO:0051701,3.970306,30.000,biological process involved in interaction wit...,Interaction
80,No effect,GO:0055085,3.362784,88.649,transmembrane transport,Transport
75,Important,GO:0006163,2.597413,13.208,purine nucleotide MP,Metabolic process
16,No effect,GO:0006865,2.589468,95.960,amino acid transport,Transport
104,No effect,GO:0006974,2.141778,84.926,cellular response to DNA damage stimulus,Response to stimulus
51,No effect,GO:0044282,1.734188,89.333,small molecule catabolic process,Catabolic process
0,No effect,GO:1901700,1.714804,86.905,BP involved in interaction with host,Response to stimulus
19,No effect,GO:1901565,1.656866,88.835,organonitrogen compound catabolic process,Catabolic process
90,No effect,GO:0006355,1.522411,80.805,regulation of DNA-templated transcription,Metabolic process
92,No effect,GO:0010035,1.418651,86.316,response to inorganic substance,NaN
60,No effect,GO:0062197,1.164029,89.286,cellular response to chemical stress,Response to stimulus
113,Important,GO:0050789,1.066431,7.980,regulation of biological process,Biological regulation
98,No effect,GO:0046395,0.912285,89.418,carboxylic acid catabolic process,Catabolic process
89,Important,GO:0046496,0.772443,25.926,nicotinamide nucleotide MP,Metabolic process

In [65]:
categorias_fit = ["Essential", "Important", "No effect", "Enhancing"]

fig = make_subplots(rows=2, cols=2, subplot_titles=categorias_fit, shared_yaxes=False, shared_xaxes=False,
                   vertical_spacing=0.17, horizontal_spacing=0.66)

categorias_go = {
    "Metabolic process": ['GO:0006355', 'GO:0006090','GO:0009185','GO:0006760','GO:0006310','GO:0022900','GO:0017148',
                         'GO:0006575','GO:0006163','GO:0046496'],
    "Cellular process": ['GO:0016226', 'GO:0051301','GO:0032506','GO:0042710','GO:0042364','GO:0019058'],
    "Catabolic process": ['GO:0044282', 'GO:1901565', 'GO:0046395', 'GO:0044275', 'GO:0006402'],
    "Biosynthetic process": ['GO:1901566', 'GO:0043604', 'GO:0008652', 'GO:1901607', 'GO:0044272', 'GO:0000097', 
                             'GO:0009067', 'GO:0009070', 'GO:0019438', 'GO:0046394', 'GO:0009244', 'GO:0044272',
                            'GO:0072528', 'GO:1901576', 'GO:0044249', 'GO:0044283'],
    "Translation": ['GO:0006412', 'GO:0000028', 'GO:0000027'],
    "Transport": ['GO:0055085', 'GO:0015849', 'GO:0006865', 'GO:0046942', 'GO:1902600', 'GO:0008643', 'GO:0009401',
                 'GO:0034219', 'GO:0030001', 'GO:0098660', 'GO:0015833','GO:0098655','GO:0098739','GO:1905039',
                 'GO:0000041'],
    "Response to stimulus": ['GO:0009628', 'GO:0009314', 'GO:0006974', 'GO:1901700','GO:0062197'],
    "Biological regulation": ['GO:0050790', 'GO:0050790','GO:0050789'],
    "Interaction" : ['GO:0044403', 'GO:0044010', 'GO:0051701']
   # "Viral process" : ['GO:0019058']
}
        
color_discrete_map = {
    'Metabolic process': 'blue',
    'Cellular process': 'red',
    'Catabolic process': 'green',
    'Biosynthetic process': 'purple',
    'Translation': 'orange',
    'Transport': 'cyan',
    'Response to stimulus': 'pink',
    'Biological regulation': 'yellow',
    'Interaction' : 'brown'
}

## Recalculate the PF by process, assign each gene a FP_new = PF/frequency

In [66]:
df_func_ygen = pd.merge(df_PL, df_gen, on=['Categ', 'GO'], how='left')
PL_sort2 = df_func_ygen.sort_values(by=['Categ','PF'], ascending=False)
PL_sort2.head()

,Categ,GO,PF,genes
82,No effect,GO:0055085,3.362784,arnE;sgcB;glvC;ytfR;ghxQ;gntU;ydfJ;yaaJ;caiT;y...
16,No effect,GO:0006865,2.589468,yaaJ;bcr;glnH;metQ;metI;metN;yahN;yqeG;brnQ;pr...
106,No effect,GO:0006974,2.141778,hokE;dinQ;tisB;apaG;polB;rihC;mutT;yadC;argF;y...
53,No effect,GO:0044282,1.734188,ygcU;glcF;glcE;cyuA;tdcG;dgoD;dgoA;mhpD;idnD;a...
0,No effect,GO:1901700,1.714804,cyuA;tatD;yaaA;kefC;nhaB;rclC;frmA;frmB;yaiW;d...

In [67]:
PL_sort2 = PL_sort2[PL_sort2['GO'] != 'GO:0019058']
PL_sort2.head()

,Categ,GO,PF,genes
82,No effect,GO:0055085,3.362784,arnE;sgcB;glvC;ytfR;ghxQ;gntU;ydfJ;yaaJ;caiT;y...
16,No effect,GO:0006865,2.589468,yaaJ;bcr;glnH;metQ;metI;metN;yahN;yqeG;brnQ;pr...
106,No effect,GO:0006974,2.141778,hokE;dinQ;tisB;apaG;polB;rihC;mutT;yadC;argF;y...
53,No effect,GO:0044282,1.734188,ygcU;glcF;glcE;cyuA;tdcG;dgoD;dgoA;mhpD;idnD;a...
0,No effect,GO:1901700,1.714804,cyuA;tatD;yaaA;kefC;nhaB;rclC;frmA;frmB;yaiW;d...

In [68]:
result_df = pd.DataFrame(columns=['Categ', 'gene', 'Frequency'])

# Calcular la frecuencia de cada gen por categoría
for category in PL_sort2['Categ'].unique():
    # Filtrar por categoría
    category_df = PL_sort2[PL_sort2['Categ'] == category]
    
    # Obtener el conjunto de genes y contar frecuencias
    genes_list = category_df['genes'].str.split(';').explode()
    genes_counts = genes_list.value_counts().reset_index()
    genes_counts.columns = ['gene', 'Frequency']
    genes_counts['Categ'] = category
    
    result_df = pd.concat([result_df, genes_counts], ignore_index=True)
result_df

          Categ  gene Frequency
0     No effect  gntP        10
1     No effect  dgoT         9
2     No effect  idnT         9
3     No effect  gatZ         9
4     No effect  proQ         8
...         ...   ...       ...
2103  Enhancing  iscR         1
2104  Enhancing  grpE         1
2105  Enhancing  yebG         1
2106  Enhancing  pykF         1
2107  Enhancing  sufE         1

[2108 rows x 3 columns]

In [69]:
proteomic_df = pd.read_csv('./infiles/proteomicf_2346.csv')
result_df = result_df.merge(proteomic_df[['gene', 'Glucose']], how='left', left_on='gene', right_on='gene')
result_df['Glucose'] = result_df['Glucose'].fillna(0)
result_df

          Categ  gene Frequency   Glucose
0     No effect  gntP        10  0.000000
1     No effect  dgoT         9  0.000000
2     No effect  idnT         9  0.000000
3     No effect  gatZ         9  0.110429
4     No effect  proQ         8  0.099541
...         ...   ...       ...       ...
2103  Enhancing  iscR         1  0.220931
2104  Enhancing  grpE         1  0.213432
2105  Enhancing  yebG         1  0.005264
2106  Enhancing  pykF         1  0.749133
2107  Enhancing  sufE         1  0.000123

[2108 rows x 4 columns]

In [70]:
# get 'PL_gen' PL/Frequency
result_df['PL_gen'] = result_df['Glucose'] / result_df['Frequency']
result_df

          Categ  gene Frequency   Glucose    PL_gen
0     No effect  gntP        10  0.000000       0.0
1     No effect  dgoT         9  0.000000       0.0
2     No effect  idnT         9  0.000000       0.0
3     No effect  gatZ         9  0.110429   0.01227
4     No effect  proQ         8  0.099541  0.012443
...         ...   ...       ...       ...       ...
2103  Enhancing  iscR         1  0.220931  0.220931
2104  Enhancing  grpE         1  0.213432  0.213432
2105  Enhancing  yebG         1  0.005264  0.005264
2106  Enhancing  pykF         1  0.749133  0.749133
2107  Enhancing  sufE         1  0.000123  0.000123

[2108 rows x 5 columns]

In [71]:
#Ahora volver a sumar PF con los nuevos valores
tgenrich_proteo = result_df['Glucose'].sum(numeric_only=True)
tgenrich_proteo    # Es lo que suma cuando hay genes en diferentes procesos

155.5992709363034

In [72]:
genrich_uniq = result_df['PL_gen'].sum()  #esto es lo que suma si se ajusta la PL/freq == comparar con el fnal
genrich_uniq

68.35134785168444

In [73]:
eco_db4691_final = "~/Notebooks/LIZ/Ntbooks_finales/infiles/allgen4691_fitfg_newname.csv"
all_db =  pd.read_csv(eco_db4691_final)
total_proteo = all_db.sum(numeric_only=True)
print(total_proteo[11])

242.9413459379637

In [74]:
Tot_prote_glu = total_proteo[11]  #242.94
lista2 = list(result_df["gene"])
tgenes = len(lista2)
matching_genes = all_db[all_db["gene"].isin(lista2)]
print('Genes enriquecidos en todos los procesos y todas las categorias =', len(matching_genes))
PL = matching_genes['Glucose'].sum(numeric_only=True)
print('carga proteomica en fg =', PL)
proteome_fraction = (PL / Tot_prote_glu) * 100
print('en PF corresponde al =', proteome_fraction, '%')

Genes enriquecidos en todos los procesos y todas las categorias = 2108
carga proteomica en fg = 155.59927093630338
en PF corresponde al = 64.04808137353304 %

In [75]:
matching_genes

,bnum,gene,gen_fit,Glucose_fit,LB_fit,Glucosamine_fit,Glycerol_fit,Xylose_fit,Succinate_fit,Mannose_fit,...,LB,Glucosamine,Glycerol,Xylose,Succinate,Mannose,Galactose,Fructose,Acetate,Pyruvate
1,b0764,modB,modB,0.205,0.2980,0.0055,0.2025,0.1705,0.4540,0.6210,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
2,b2413,cysZ,cysZ,-0.196,0.0470,0.0100,-0.2310,-0.1020,-0.0600,-0.1500,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
3,b3639,dfp,dfp,0.000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,...,0.042918,0.024835,0.017690,0.019203,0.013245,0.016354,0.013236,0.020423,0.016088,0.030884
4,b4123,dcuB,dcuB,0.035,0.0260,-0.0975,-0.0520,-0.1515,-0.1485,-0.1670,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
5,b2307,hisM,hisM,0.046,0.0215,0.0310,-0.0190,-0.0490,-0.2005,-0.0970,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4652,b0350,mhpD,mhpD,-0.145,0.1470,-0.0070,-0.1205,0.0100,0.0005,0.0140,...,0.000613,0.000494,0.000099,0.000000,0.000259,0.000000,0.000258,0.000000,0.000163,0.000186
4653,b0351,mhpF,mhpF,-0.004,0.3785,0.0940,-0.0470,-0.0775,0.2290,0.2810,...,0.011136,0.007528,0.005345,0.000000,0.007556,0.000000,0.003172,0.000000,0.004275,0.004541
4654,b2539,hcaF,hcaF,-0.094,0.2385,0.1965,0.3385,0.2340,0.1745,0.1430,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
4655,b1861,ruvA,ruvA,-0.724,-0.4740,-1.0070,-1.2770,-1.2360,-1.5255,-0.9930,...,0.009217,0.009585,0.006661,0.000000,0.007150,0.000000,0.003163,0.000000,0.004247,0.006035
4656,b1860,ruvB,ruvB,-0.620,-0.5785,-0.4115,-1.3280,-0.3490,-1.5405,-0.7785,...,0.021316,0.010081,0.010597,0.009038,0.009398,0.010892,0.007433,0.009994,0.010509,0.011084

In [76]:
PL_sort2['len_genes'] = PL_sort2['genes'].apply(lambda x: len(x.split(';')))
#primero separar los genes de la col genes
gen_spl = PL_sort2.reset_index()
gen_spl['genes'] = gen_spl['genes'].str.split(';') 
gen_spl.head()

,index,Categ,GO,PF,genes,len_genes
0,82,No effect,GO:0055085,3.362784,"[arnE, sgcB, glvC, ytfR, ghxQ, gntU, ydfJ, yaa...",492
1,16,No effect,GO:0006865,2.589468,"[yaaJ, bcr, glnH, metQ, metI, metN, yahN, yqeG...",95
2,106,No effect,GO:0006974,2.141778,"[hokE, dinQ, tisB, apaG, polB, rihC, mutT, yad...",231
3,53,No effect,GO:0044282,1.734188,"[ygcU, glcF, glcE, cyuA, tdcG, dgoD, dgoA, mhp...",268
4,0,No effect,GO:1901700,1.714804,"[cyuA, tatD, yaaA, kefC, nhaB, rclC, frmA, frm...",73

In [77]:
#Recalcular la PF con los nuevos genes filtrados. 
df_PFnew = pd.DataFrame(columns=['Categ', 'GO','PF_new','len_genes'])

for index, row in gen_spl.iterrows():
    cat = row['Categ']
    go = row['GO']
    len_gen = row['len_genes']
    ls_gen = row['genes']
    #print(ls_gen)
    matching_genes = result_df[result_df["gene"].isin(ls_gen)]
   # print(matching_genes)
    PL = matching_genes['PL_gen'].sum()
   # print(PL)
    proteome_fraction = (PL / Tot_prote_glu) * 100
    proteome_fraction
    
    df_PFnew = pd.concat([df_PFnew, pd.DataFrame({'Categ': [cat], 'GO': [go], 'PF_new': [proteome_fraction], 
                                                  'len_genes': [len_gen]})], ignore_index=True)
df_PFnew.sort_values(by='PF_new', ascending=False)
df_PFnew.head()

       Categ          GO    PF_new len_genes
0  No effect  GO:0055085  1.627441       492
1  No effect  GO:0006865  1.930948        95
2  No effect  GO:0006974  1.773692       231
3  No effect  GO:0044282  0.810706       268
4  No effect  GO:1901700  1.212939        73

In [78]:
total_sum = df_PFnew['PF_new'].sum()
total_sum

64.04808137353304

In [79]:
PL_sort3 = pd.merge(df_PFnew, df_fil[['Categ', 'GO', 'percent']], on=['Categ', 'GO'], how='left')
df_func2 = pd.merge(PL_sort3, funciones, on='GO', how='left')
df_func2.head(10)

,Categ,GO,PF_new,len_genes,percent,term
0,No effect,GO:0055085,1.627441,492,88.649,transmembrane transport
1,No effect,GO:0006865,1.930948,95,95.960,amino acid transport
2,No effect,GO:0006974,1.773692,231,84.926,cellular response to DNA damage stimulus
3,No effect,GO:0044282,0.810706,268,89.333,small molecule catabolic process
4,No effect,GO:1901700,1.212939,73,86.905,response to oxygen-containing compound
5,No effect,GO:1901565,1.010364,183,88.835,organonitrogen compound catabolic process
6,No effect,GO:0006355,1.390581,261,80.805,regulation of DNA-templated transcription
7,No effect,GO:0010035,0.729800,82,86.316,response to inorganic substance
8,No effect,GO:0062197,0.722654,50,89.286,cellular response to chemical stress
9,No effect,GO:0046395,0.285062,169,89.418,carboxylic acid catabolic process

In [80]:
df_func2 = df_func2[df_func2['GO'] != 'GO:0006757']
df_func2 = df_func2[df_func2['GO'] != 'GO:0010035']
PL_sort2.head(10)

,Categ,GO,PF,genes,len_genes
82,No effect,GO:0055085,3.362784,arnE;sgcB;glvC;ytfR;ghxQ;gntU;ydfJ;yaaJ;caiT;y...,492
16,No effect,GO:0006865,2.589468,yaaJ;bcr;glnH;metQ;metI;metN;yahN;yqeG;brnQ;pr...,95
106,No effect,GO:0006974,2.141778,hokE;dinQ;tisB;apaG;polB;rihC;mutT;yadC;argF;y...,231
53,No effect,GO:0044282,1.734188,ygcU;glcF;glcE;cyuA;tdcG;dgoD;dgoA;mhpD;idnD;a...,268
0,No effect,GO:1901700,1.714804,cyuA;tatD;yaaA;kefC;nhaB;rclC;frmA;frmB;yaiW;d...,73
19,No effect,GO:1901565,1.656866,cyuA;tdcG;sspB;rihC;ldcC;ltaE;mltA;ybcF;eutH;y...,183
92,No effect,GO:0006355,1.522411,torI;greB;dgoR;sspA;dnaK;yfaX;dnaJ;nhaR;araC;s...,261
94,No effect,GO:0010035,1.418651,arnE;tatD;nhaB;gshA;rclC;cusR;asr;mscK;cusF;cu...,82
62,No effect,GO:0062197,1.164029,setA;yajL;loiP;mltC;grxA;treA;ychH;tpx;mdtK;us...,50
100,No effect,GO:0046395,0.912285,ygcU;glcF;glcE;cyuA;tdcG;dgoD;dgoA;mhpD;idnD;l...,169

In [81]:
PL_sort3 = df_func2.sort_values(by=['PF_new'], ascending=False)
#PL_sort3.to_csv('tbl_distribution_of_PF')
top_PLn = PL_sort3.groupby('Categ').head(15)
topPLn = top_PLn.copy()
topPLn.head(10)

,Categ,GO,PF_new,len_genes,percent,term
64,Essential,GO:1901576,5.976889,292,25.864,organic substance biosynthetic process
65,Essential,GO:0044249,5.631095,294,26.703,cellular biosynthetic process
66,Essential,GO:1901566,4.479029,222,40.809,organonitrogen compound biosynthetic process
45,Important,GO:0051701,3.967561,6,30.000,biological process involved in interaction wit...
68,Essential,GO:0043604,2.734927,87,43.939,amide biosynthetic process
69,Essential,GO:0006412,2.520047,75,51.370,translation
67,Essential,GO:0044283,2.184901,113,37.171,small molecule biosynthetic process
46,Important,GO:0006163,2.116786,14,13.208,purine nucleotide metabolic process
1,No effect,GO:0006865,1.930948,95,95.960,amino acid transport
2,No effect,GO:0006974,1.773692,231,84.926,cellular response to DNA damage stimulus

In [82]:
categorias = {
    "Metabolic process": ['GO:0006355', 'GO:0006090','GO:0009185','GO:0006760','GO:0006310','GO:0022900','GO:0017148',
                         'GO:0006575','GO:0006163','GO:0046496'],  #GO:0006757,
    "Cellular process": ['GO:0016226', 'GO:0051301','GO:0032506','GO:0042710','GO:0042364','GO:0009061','GO:0019058'],
     
    "Catabolic process": ['GO:0044282', 'GO:1901565', 'GO:0046395', 'GO:0044275', 'GO:0006402'],
    "Biosynthetic process": ['GO:1901566', 'GO:0043604', 'GO:0008652', 'GO:1901607', 'GO:0044272', 'GO:0000097', 
                             'GO:0009067', 'GO:0009070', 'GO:0019438', 'GO:0046394', 'GO:0009244', 'GO:0044272',
                            'GO:0072528', 'GO:1901576', 'GO:0044249', 'GO:0044283'],
    "Translation": ['GO:0006412', 'GO:0000028', 'GO:0000027'],
    "Transport": ['GO:0055085', 'GO:0015849', 'GO:0006865', 'GO:0046942', 'GO:1902600', 'GO:0008643', 'GO:0009401',
                 'GO:0034219', 'GO:0030001', 'GO:0098660', 'GO:0015833','GO:0098655','GO:0098739','GO:1905039',
                 'GO:0000041'],
    "Response to stimulus": ['GO:0009628', 'GO:0009314', 'GO:0006974', 'GO:1901700','GO:0062197'],
    "Biological regulation": ['GO:0050790', 'GO:0050790','GO:0050789'],
    "Interaction" : ['GO:0044403', 'GO:0044010', 'GO:0051701'],  
}

topPLn['category'] = topPLn['GO'].map({GO: categoria for categoria, valores in categorias.items() for GO in valores})
for categoria in categorias:
    subset_df = topPLn[topPLn['category'] == categoria]
  #  print(subset_df)

In [83]:
topPLn['term'] = topPLn['term'].replace('biosynthetic process', 'biosyn', regex=True)  #abbreviations: biosynth=biosynthetic
topPLn['term'] = topPLn['term'].replace('metabolic process', 'MP', regex=True)
topPLn['term'] = topPLn['term'].replace('biological process', 'BP', regex=True)
topPLn

,Categ,GO,PF_new,len_genes,percent,term,category
64,Essential,GO:1901576,5.976889,292,25.864,organic substance biosyn,Biosynthetic process
65,Essential,GO:0044249,5.631095,294,26.703,cellular biosyn,Biosynthetic process
66,Essential,GO:1901566,4.479029,222,40.809,organonitrogen compound biosyn,Biosynthetic process
45,Important,GO:0051701,3.967561,6,30.000,BP involved in interaction with host,Interaction
68,Essential,GO:0043604,2.734927,87,43.939,amide biosyn,Biosynthetic process
69,Essential,GO:0006412,2.520047,75,51.370,translation,Translation
67,Essential,GO:0044283,2.184901,113,37.171,small molecule biosyn,Biosynthetic process
46,Important,GO:0006163,2.116786,14,13.208,purine nucleotide MP,Metabolic process
1,No effect,GO:0006865,1.930948,95,95.960,amino acid transport,Transport
2,No effect,GO:0006974,1.773692,231,84.926,cellular response to DNA damage stimulus,Response to stimulus
0,No effect,GO:0055085,1.627441,492,88.649,transmembrane transport,Transport
70,Essential,GO:0008652,1.414044,68,48.227,amino acid biosyn,Biosynthetic process
6,No effect,GO:0006355,1.390581,261,80.805,regulation of DNA-templated transcription,Metabolic process
71,Essential,GO:1901607,1.314541,54,45.378,alpha-amino acid biosyn,Biosynthetic process
77,Essential,GO:0009185,1.252660,10,43.478,ribonucleoside diphosphate MP,Metabolic process
76,Essential,GO:0006090,1.249694,14,41.176,pyruvate MP,Metabolic process
4,No effect,GO:1901700,1.212939,73,86.905,response to oxygen-containing compound,Response to stimulus
92,Essential,GO:0051301,1.177978,27,29.348,cell division,Cellular process
5,No effect,GO:1901565,1.010364,183,88.835,organonitrogen compound catabolic process,Catabolic process
3,No effect,GO:0044282,0.810706,268,89.333,small molecule catabolic process,Catabolic process
47,Important,GO:0050789,0.804199,49,7.980,regulation of BP,Biological regulation
72,Essential,GO:0044272,0.772246,22,35.484,sulfur compound biosyn,Biosynthetic process
8,No effect,GO:0062197,0.722654,50,89.286,cellular response to chemical stress,Response to stimulus
81,Essential,GO:0000028,0.620774,13,61.905,ribosomal small subunit assembly,Translation
73,Essential,GO:0000097,0.545016,10,38.462,sulfur amino acid biosyn,Biosynthetic process
74,Essential,GO:0009067,0.511747,18,50.000,aspartate family amino acid biosyn,Biosynthetic process
117,Enhancing,GO:0009628,0.501527,8,3.162,response to abiotic stimulus,Response to stimulus
118,Enhancing,GO:0006355,0.425167,9,2.786,regulation of DNA-templated transcription,Metabolic process
48,Important,GO:0046496,0.383613,7,25.926,nicotinamide nucleotide MP,Metabolic process
14,No effect,GO:0022900,0.376840,88,90.722,electron transport chain,Metabolic process
49,Important,GO:0032506,0.291821,6,30.000,cytokinetic process,Cellular process
9,No effect,GO:0046395,0.285062,169,89.418,carboxylic acid catabolic process,Catabolic process
18,No effect,GO:0042710,0.248193,102,90.265,biofilm formation,Cellular process
51,Important,GO:0000041,0.247486,9,13.235,transition metal ion transport,Transport
10,No effect,GO:0098655,0.243719,91,85.047,monoatomic cation transmembrane transport,Transport
50,Important,GO:0006402,0.154371,5,25.000,mRNA catabolic process,Catabolic process
52,Important,GO:0009244,0.152839,7,28.000,lipopolysaccharide core region biosyn,Biosynthetic process
15,No effect,GO:1905039,0.122601,83,95.402,carboxylic acid transmembrane transport,Transport
11,No effect,GO:0008643,0.122535,115,92.742,carbohydrate transport,Transport
53,Important,GO:0098660,0.116934,15,12.821,inorganic ion transmembrane transport,Transport
29,No effect,GO:0009061,0.115884,58,95.082,anaerobic respiration,Cellular process
54,Important,GO:0044272,0.097420,10,16.129,sulfur compound biosyn,Biosynthetic process
55,Important,GO:0006310,0.067066,12,11.429,DNA recombination,Metabolic process
56,Important,GO:0072528,0.063126,9,23.684,pyrimidine-containing compound biosyn,Biosynthetic process
60,Important,GO:0042364,0.057726,11,16.667,water-soluble vitamin biosyn,Cellular process
59,Important,GO:0009314,0.051587,13,13.402,response to radiation,Response to stimulus
57,Important,GO:0050790,0.050475,10,14.286,regulation of catalytic activity,Biological regulation
119,Enhancing,GO:0016226,0.023957,4,19.048,iron-sulfur cluster assembly,Cellular process

In [84]:
asum = PL_sort3['PF_new'].sum()
print(f'La PF de todas las categorias y todos los procesos es: {asum:.2f} %')
sumPB_xcateg = PL_sort3.groupby('Categ')['PF_new'].sum().reset_index()
sumPB_xcateg

La PF de todas las categorias y todos los procesos es: 62.09 %

       Categ     PF_new
0  Enhancing   0.950651
1  Essential  39.009491
2  Important   8.723361
3  No effect  13.401887

In [85]:
categorias_fit = ["Essential", "Important", "No effect", "Enhancing"]
lt = ['a)', 'b)', 'c)', 'd)']
subplot_titles = [f"{lt[i]} {titulo}" for i, titulo in enumerate(categorias_fit)]


fig = make_subplots(rows=2, cols=2, subplot_titles=categorias_fit, shared_yaxes=False, shared_xaxes=False,
                   vertical_spacing=0.17, horizontal_spacing=0.66)

categorias_go = {
    "Metabolic process": ['GO:0006355', 'GO:0006090','GO:0009185','GO:0006760','GO:0006310','GO:0022900','GO:0017148',
                         'GO:0006575','GO:0006163','GO:0046496'],
    "Cellular process": ['GO:0016226', 'GO:0051301','GO:0032506','GO:0042710','GO:0042364','GO:0009061'],
     
    "Catabolic process": ['GO:0044282', 'GO:1901565', 'GO:0046395', 'GO:0044275', 'GO:0006402'],
    "Biosynthetic process": ['GO:1901566', 'GO:0043604', 'GO:0008652', 'GO:1901607', 'GO:0044272', 'GO:0000097', 
                             'GO:0009067', 'GO:0009070', 'GO:0019438', 'GO:0046394', 'GO:0009244', 'GO:0044272',
                            'GO:0072528', 'GO:1901576', 'GO:0044249', 'GO:0044283'],
    "Translation": ['GO:0006412', 'GO:0000028', 'GO:0000027'],
    "Transport": ['GO:0055085', 'GO:0015849', 'GO:0006865', 'GO:0046942', 'GO:1902600', 'GO:0008643', 'GO:0009401',
                 'GO:0034219', 'GO:0030001', 'GO:0098660', 'GO:0015833','GO:0098655','GO:0098739','GO:1905039',
                 'GO:0000041'],
    "Response to stimulus": ['GO:0009628', 'GO:0009314', 'GO:0006974', 'GO:1901700','GO:0062197'],
    "Biological regulation": ['GO:0050790', 'GO:0050790','GO:0050789'],
    "Interaction" : ['GO:0044403', 'GO:0044010', 'GO:0051701']
   # "Viral process" : ['GO:0019058']
}
        
color_discrete_map = {
    'Metabolic process': 'blue',
    'Cellular process': 'red',
    'Catabolic process': 'green',
    'Biosynthetic process': 'purple',
    'Translation': 'orange',
    'Transport': 'cyan',
    'Response to stimulus': 'pink',
    'Biological regulation': 'yellow',
    'Interaction' : 'brown'
}

In [86]:
import plotly.graph_objects as go
from plotly.subplots import make_subplots

lt = ['a)', 'b)', 'c)', 'd)']
subplot_titles = [f"{lt[i]} {titulo}" for i, titulo in enumerate(categorias_fit)]

fig = make_subplots(rows=2, cols=2, subplot_titles=subplot_titles, 
                    shared_yaxes=False, shared_xaxes=False, vertical_spacing=0.15, horizontal_spacing=0.55)
rangos = [(0, 6.2), (0, 4.2), (0, 2.1), (0, 0.63)]

for i, categoria in enumerate(categorias_fit):
    row = i // 2 + 1
    col = i % 2 + 1

    k = False
    for j, catgo in enumerate(categorias_go):
        subset_df = topPLn[(topPLn['category'] == catgo) & (topPLn['Categ'] == categoria)]
        y_column = subset_df["term"]
        x_column = subset_df["PF_new"]
        category_color = color_discrete_map[catgo]
               
        trace = go.Bar(x=x_column, y=y_column, name=catgo, orientation='h', marker_color=category_color,
                       showlegend=k)
        fig.add_trace(trace, row=row, col=col)       
    fig.update_xaxes(title_text="Proteome fraction (%)", row=row, col=col, title_font=dict(size=10), tickfont=dict(size=10))
    fig.update_xaxes(range=rangos[i], row=row, col=col, showgrid=True)
    fig.update_yaxes(row=row, col=col, title_font=dict(size=9), tickfont=dict(size=9))  
    
# Añadir leyenda al final
for catgo, color in color_discrete_map.items():
    fig.add_trace(go.Scatter(
        x=[None],
        y=[None],
        mode='markers',
        marker=dict(size=9, color=color, opacity=0.9, symbol='square'),
        legendgroup=catgo,
        name=catgo
    ))

# legend and subplots
fig.update_layout(legend_title_text='  GO Biological Process')
fig.update_layout(
    legend=dict(
        x=1,
        y=1,
        title_font_family="Times New Roman",
        font=dict(
            family="Times New Roman",
            size=12,
            color="black"
        ),
        bgcolor="White"
    )
)
fig.update_layout(height=700, width=800, 
                  #title_text='GO process with highest proteome fraction', 
                  title_x=0.7, bargap=0.2, margin=dict(l=235, r=50, t=80), font={'color': 'black'})

# Ordenar las categorías de los ejes Y en orden ascendente por total y revertir ejes Y
for i in range(1, len(categorias_fit)//2 + 2):
    for j in range(1, 3):
        fig.update_yaxes(row=i, col=j, autorange='reversed')
fig.write_image("./Figures/Fig04_top15GOterm_PF.svg")
fig.show()

In [87]:
# -------------------

In [88]:
# Modified by David.
categorias_fit_plot = ["Essential", "Important", "No-effect", "Enhancing"]

lt = ['A   ', 'B   ', 'C   ', 'D   ']
subplot_titles = [f"{lt[i]} {titulo}" for i, titulo in enumerate(categorias_fit_plot)]

fig = make_subplots(rows=2, cols=2, subplot_titles=subplot_titles, 
                    shared_yaxes=False, shared_xaxes=False, vertical_spacing=0.15, horizontal_spacing=0.55)
rangos = [(0, 6.2), (0, 4.2), (0, 2.1), (0, 0.63)]

for i, categoria in enumerate(categorias_fit):
    row = i // 2 + 1
    col = i % 2 + 1

    k = False
    for j, catgo in enumerate(categorias_go):
        subset_df = topPLn[(topPLn['category'] == catgo) & (topPLn['Categ'] == categoria)]
        y_column = subset_df["term"]
        x_column = subset_df["PF_new"]
        category_color = color_discrete_map[catgo]
               
        trace = go.Bar(x=x_column, y=y_column, name=catgo, orientation='h', marker_color=category_color,
                       showlegend=k)
        fig.add_trace(trace, row=row, col=col)       
    fig.update_xaxes(title_text="Proteome fraction (%)", row=row, col=col, title_font=dict(size=10), tickfont=dict(size=10))
    fig.update_xaxes(range=rangos[i], row=row, col=col, showgrid=True)
    fig.update_yaxes(row=row, col=col, title_font=dict(size=9), tickfont=dict(size=9))  
    
# Añadir leyenda al final
for catgo, color in color_discrete_map.items():
    fig.add_trace(go.Scatter(
        x=[None],
        y=[None],
        mode='markers',
        marker=dict(size=9, color=color, opacity=0.9, symbol='square'),
        legendgroup=catgo,
        name=catgo
    ))

# Modify legend positioning
fig.update_layout(
    legend=dict(
        x=1.1,  # Move the legend more to the right
        y=0.5,  # Move the legend to be centered vertically
        font=dict(
            size=12,
            color="black"
        ),
        bgcolor="White"
    ),
    legend_title_text='  GO Biological Process'
)
fig.update_layout(height=700, width=800, 
                  title_x=0.7, bargap=0.2, margin=dict(l=235, r=50, t=80), font={'color': 'black'})

# Ordenar las categorías de los ejes Y en orden ascendente por total y revertir ejes Y
for i in range(1, len(categorias_fit)//2 + 2):
    for j in range(1, 3):
        fig.update_yaxes(row=i, col=j, autorange='reversed')
fig.write_image("./Figures/Fig04_top15GOterm_PF.svg")
fig.write_image("./Figures/Fig04_top15GOterm_PF.png")
#fig.show()

In [89]:
# ------------------

In [90]:
sum_top = topPLn['PF_new'].sum()
print(f'La PF del top de todas las categorías es: {sum_top:.2f} %')
#sumar para cada categoria
sumPB_xcateg = topPLn.groupby('Categ')['PF_new'].sum().reset_index()
sumPB_xcateg  #la suma de esto la suma del top. es decir solo lo que esta en la figura

La PF del top de todas las categorías es: 53.95 %

       Categ     PF_new
0  Enhancing   0.950651
1  Essential  32.385587
2  Important   8.623009
3  No effect  11.994159